spring:
  datasource:
    username: dbuser
    passsword: '{cipher}AQBB/9DoLNk94oBKLfPa9YErvVst7osS1wYVSlcswNlFkDXPTnlKcw9+rxoiKVE1x+UoeRDS/+Rm5cSOV1eqf76D9L7pI4Ez17jd3XV5ip2o7K7x5QHNaQn4cXRZ8Od6hS4l3R4GmBGHmQEK1Jgcz1eUFdRbLGryEZzz8PPwF8C7/qG2O0dWlTxjU9ioxcTWcuWCZB2/db8z5HQMrnVYQgHRD1mdLuEzAEr/3b7u/aZQRYZbTuw9fuOYJpUZUjvA0m+dhIVYAGst3Tl0sHEjd2yKILZTxei5jBjwjfVD+NSZpA0Tv1BQI77GxA9jxLQM'